"""add bank_ref to transactions

Revision ID: 7900c46cfab1
Revises: 7b81e179cf9b
Create Date: 2026-05-15 00:44:21.954172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7900c46cfab1'
down_revision: Union[str, None] = '7b81e179cf9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('bank_ref', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transactions_bank_ref'), 'transactions', ['bank_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_bank_ref'), table_name='transactions')
    op.drop_column('transactions', 'bank_ref')
    # ### end Alembic commands ###
