"""add income table

Revision ID: 7b81e179cf9b
Revises: bb9c2f28f962
Create Date: 2026-05-15 00:21:17.371163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b81e179cf9b'
down_revision: Union[str, None] = 'bb9c2f28f962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_date'), 'income', ['date'], unique=False)
    op.create_index(op.f('ix_income_household_id'), 'income', ['household_id'], unique=False)
    op.create_index(op.f('ix_income_month'), 'income', ['month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_month'), table_name='income')
    op.drop_index(op.f('ix_income_household_id'), table_name='income')
    op.drop_index(op.f('ix_income_date'), table_name='income')
    op.drop_table('income')
    # ### end Alembic commands ###
