"""add_rollover

Revision ID: b344abc09eca
Revises: c389fa236ed7
Create Date: 2026-05-15 07:44:20.525323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b344abc09eca'
down_revision: Union[str, None] = 'c389fa236ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('envelopes', sa.Column('rollover', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('periods', sa.Column('rollover', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periods', 'rollover')
    op.drop_column('envelopes', 'rollover')
    # ### end Alembic commands ###
