"""add_bank_ref_to_income

Revision ID: c389fa236ed7
Revises: 7900c46cfab1
Create Date: 2026-05-15 06:52:23.687591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c389fa236ed7'
down_revision: Union[str, None] = '7900c46cfab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('bank_ref', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_income_bank_ref'), 'income', ['bank_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_bank_ref'), table_name='income')
    op.drop_column('income', 'bank_ref')
    # ### end Alembic commands ###
